# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutifyCli < Formula
  desc "Autify client"
  homepage "https://github.com/koukikitamura/autify-cli"
  version "1.1.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koukikitamura/autify-cli/releases/download/v1.1.1/autify-cli_darwin_x86_64.tar.gz"
      sha256 "25ad888521611022b1a051b566269842e3a0a55022493a8e3821c818b050fd4d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koukikitamura/autify-cli/releases/download/v1.1.1/autify-cli_linux_x86_64.tar.gz"
      sha256 "bc4d73d063ebb67ffdfa096db30b300adb3da0b5645f543afe83983b1d9c836c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koukikitamura/autify-cli/releases/download/v1.1.1/autify-cli_linux_arm64.tar.gz"
      sha256 "b920fb577d9026512150a0aa0b230c49ca7a779538e1c27897ce3d846cb62bdf"
    end
  end

  def install
    bin.install "atf"
  end
end
