# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutifyCli < Formula
  desc "Autify client"
  homepage "https://github.com/koukikitamura/autify-cli"
  version "1.0.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koukikitamura/autify-cli/releases/download/v1.0.0/autify-cli_darwin_x86_64.tar.gz"
      sha256 "3acfb0719fd826fc53edb8042a1bb513ffdb9776d4cfdbcaf0ad86b7713dfae8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koukikitamura/autify-cli/releases/download/v1.0.0/autify-cli_linux_x86_64.tar.gz"
      sha256 "dade812fbd13053a4f093d0facf573e403ccfe665e042b4590280031eb9fe0cf"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koukikitamura/autify-cli/releases/download/v1.0.0/autify-cli_linux_arm64.tar.gz"
      sha256 "bebf3937bfabdf0815c90bba0fe4789fbb80f107fdb9ab7180926bd4f167b127"
    end
  end

  def install
    bin.install "atf"
  end
end
